[profile.default]
libs = ["node_modules", "lib"]
solc = "0.8.24"
evm_version = 'cancun'
remappings = [
  "forge-std/=dependencies/forge-std-1.9.3/src/",
]

[dependencies]
forge-std = "1.9.3"

[fmt]
# These are all the `forge fmt` defaults.
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'long'
multiline_func_header = 'attributes_first'
quote_style = 'double'
number_underscore = 'preserve'
single_line_statement_blocks = 'preserve'
ignore = ["src/console.sol", "src/console2.sol"]
